install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.11/sbt-0.13.11.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - ps: |
      if (!(Test-Path -Path "C:\Program Files\Java\jdk1.7.0\src.zip")) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://downloads.sourceforge.net/project/jdk7src/jdk7u10/2013-01-04/src-jdk.zip',
          'C:\Program Files\Java\jdk1.7.0\src.zip'
        )
      }
  - cmd: SET JDK_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET PATH=C:\sbt\sbt\bin;%JDK_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=256m -Xss2m -Xms1g -Xmx1g
  - cmd: SET AKKA_TEST_TIMEFACTOR=10
  - cmd: SET SBT_TASK_LIMIT=2
  - cmd: SET GC_LOGGING=true
build_script:
  - sbt ";ensimeConfig ;test:compile ;it:compile"
test_script:
  - sbt ";test ;it:test"
cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.coursier
  - C:\Program Files\Java\jdk1.7.0\src.zip
on_finish:
  - ps: Get-ChildItem -Path .\* -Include *.log -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
